apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080    # ✅ App container port
  selector:
    app: {{ include "spring-boot-app.name" . }}
